server:
  port: 8197
  servlet:
    context-path: /orders-service
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./orders;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
integrations:
  cart-service:
    url: http://localhost:5555/cart
    read-timeout: 5000
    write-timeout: 5000
    connect-timeout: 5000
#cart:
#  get-cart: http://localhost:8190/market-cart/api/v1/cart
#  clear-cart: http://localhost:8190/market-cart/api/v1/cart/clear