server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8199"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
      routes:
        - id: products-service
          uri: http://localhost:8191
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
            - PrefixPath=/products-service
            - JwtAuthFilter
        - id: orders-service
          uri: http://localhost:8197
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - PrefixPath=/orders-service
            - JwtAuthFilter
        - id: core-service
          uri: http://localhost:8189
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core-service
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8190
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
            - JwtAuthFilter
jwt:
  secret: kfkhgfkhgftfuuyghboggh786h984hiub9h0u9n7tn409tun4598b
  lifetime: 108000