server:
  port: 8191
  servlet:
    context-path: /products-service
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
cart:
  get-cart: http://localhost:8190/market-cart/api/v1/cart
  clear-cart: http://localhost:8190/market-cart/api/v1/cart/clear